name: CI

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/test'      
    steps:
    - uses: actions/checkout@v4

    # - uses: shuttle-hq/deploy-action@main
    #   with:
    #     deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
    #     working-directory: "try-test"
    #     name: "try-test"

    - name: Call Api
      id: api-result
      run: |
        echo "Calling Api"

        RESULT=$(curl https://try-test.shuttleapp.rs)

        echo "result=$RESULT" >> "$GITHUB_OUTPUT"

    - run: | 
        echo Result from the prev step: "${{ steps.api-result.outputs.result }}"

    - name: A/B Check
      if: ${{ steps.api-result.outputs.result }} != 'Hello world!'
      run: |
        echo "The API returned: '${{ steps.api-result.outputs.result }}'"
        exit 1
    
    # - name: Call Api
    #   run: curl https://try-test.shuttleapp.rs
    
    # - name: Set output
    #   id: setter
    #   run: |
    #     echo "foo=bar" >> "$GITHUB_OUTPUT"
      


