name: CI

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo "value=[\"actix-web-test\", \"tide-test\", \"thruster-test\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
  deploy:
    needs: [ setup ]
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v4

    - name: Deploy Actix Web
      uses: shuttle-hq/deploy-action@main
      with:

        deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
        working-directory: "deployment-tests/${{ matrix.value }}"

    - name: Call Actix Api
      id: call-api
      run: |
        echo "Calling Api"

        RESULT=$(curl https://${{ matrix.value }}.shuttleapp.rs)

        echo "result=$RESULT" >> "$GITHUB_OUTPUT"

    - name: If Api isn't returning "Hello World!"
      if: steps.call-api.outputs.result != 'Hello World!'
      run: |
        echo "The API returned: '${{ steps.call-api.outputs.result }}'"
        exit 1

      
